before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - binary: main
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
dockers:
  - binaries:
      - main
    extra_files: []
    goos: linux
    goarch: amd64
    image_templates:
      - "defn/hello:{{ .Env.SCM_VERSION }}-amd64"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --platform=linux/amd64
  - binaries:
      - main
    extra_files: []
    goos: linux
    goarch: arm64
    image_templates:
      - "defn/hello:{{ .Env.SCM_VERSION }}-arm64"
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --platform=linux/arm64/v8
docker_manifests:
  - name_template: "defn/hello:{{ .Env.SCM_VERSION }}"
    image_templates:
      - "defn/hello:{{ .Env.SCM_VERSION }}-amd64"
      - "defn/hello:{{ .Env.SCM_VERSION }}-arm64"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Env.SCM_VERSION}}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
