#!/usr/bin/env bash

function main {
  local NM_ROLE="$1"; shift

  local WRAPPED_SID="$(/env.sh vault write -field=wrapping_token -wrap-ttl=60s -f "auth/approle/role/${NM_ROLE}/secret-id")"
  /env.sh vault unwrap -field=secret_id "${WRAPPED_SID}"
}

main "$@"
